version: "2.1"

services:
  powerdns-admin:
    build:
      context: ../
    image: aaronsfoley/pdns-admin
    container_name: powerdns-admin
    mem_limit: 256M
    memswap_limit: 256M
    ports:
      - "9191:9191"
    networks:
      - default
    environment:
      - PDA_SECRET_KEY=changeme
      - PDA_DB_HOST=powerdns-admin-mysql
      - PDA_DB_NAME=powerdns-admin
      - PDA_DB_USER=powerdns
      - PDA_DB_PASSWORD=powerdns
      - PDA_DB_PORT=3306
    depends_on:
      powerdns-admin-mysql:
        condition: service_healthy

  powerdns-admin-mysql:
    image: mariadb
    hostname: powerdns-db
    container_name: powerdns-admin-mysql
    mem_limit: 256M
    memswap_limit: 256M
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - powerdns-mysql-data:/var/lib/mysql
      - ./extra.sql:/docker-entrypoint-initdb.d/extra.sql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=powerdns-admin
      - MYSQL_USER=powerdns
      - MYSQL_PASSWORD=powerdns
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  pdns-server:
    image: psitrax/powerdns
    hostname: powerdns
    ports:
      - "5053:53"
      - "5053:53/udp"
      - "8081:8081"
    networks:
      - default
    command: --api=yes --api-key=changeme --webserver-address=0.0.0.0 --webserver-allow-from=0.0.0.0/0
    environment:
      - MYSQL_HOST=powerdns-admin-mysql
      - MYSQL_USER=powerdns
      - MYSQL_PASS=powerdns
      - MYSQL_DB=powerdns
      - PDNS_API_KEY=changeme
    depends_on:
      powerdns-admin-mysql:
        condition: service_healthy

networks:
  default:

volumes:
  powerdns-mysql-data: